import "./globals.css";
import Sessionwrapper from "./components/sessionwrapper";
import { ConvexProviderWrapper } from "./components/convexwrapper";

// Using system fonts for better reliability and performance
const fontClass = 'font-sans';

// If you want to use Google Fonts in the future, you can uncomment this:
/*
import { Inter } from 'next/font/google';
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
const fontClass = inter.className;
*/

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={`${fontClass} antialiased`}>
        <ConvexProviderWrapper>
          <Sessionwrapper>
            {children}
          </Sessionwrapper>
        </ConvexProviderWrapper>  
      </body>
     
    </html>
  );
}
